#!/usr/bin/env bash
# update-gitmoji — fetch the latest gitmoji mapping from upstream and
# regenerate bin/gitmojis.txt.
#
# Usage:
#   ./scripts/update-gitmoji.sh                        # refresh file in-place
#   ./scripts/update-gitmoji.sh /path/to/output.txt    # write to a custom path
#
# The output file is a pipe-delimited mapping:
#   <emoji>|<name>|<description>
#
# Source: https://github.com/carloscuesta/gitmoji
#   (packages/gitmojis/src/gitmojis.json)

set -euo pipefail

GITMOJI_JSON_URL="https://raw.githubusercontent.com/carloscuesta/gitmoji/master/packages/gitmojis/src/gitmojis.json"

# Determine output path.
if [ $# -ge 1 ]; then
  OUTPUT="$1"
else
  OUTPUT="$(cd "$(dirname "$0")/.." && pwd)/bin/gitmojis.txt"
fi

# Fetch the JSON.
echo "Fetching gitmoji data from upstream..." >&2
if command -v python3 &>/dev/null; then
  JSON="$(python3 -c "
import urllib.request, json, sys
try:
  data = json.loads(urllib.request.urlopen('${GITMOJI_JSON_URL}').read().decode())
  for g in data['gitmojis']:
    e = g['emoji']
    n = g['name']
    d = g['description'].replace('|', '/')
    print(f'{e}|{n}|{d}')
except Exception as exc:
  print(f'ERROR: {exc}', file=sys.stderr)
  sys.exit(1)
")"
elif command -v curl &>/dev/null; then
  JSON="$(curl -sL "$GITMOJI_JSON_URL" | python3 -c "
import json, sys
data = json.load(sys.stdin)
for g in data['gitmojis']:
  e = g['emoji']
  n = g['name']
  d = g['description'].replace('|', '/')
  print(f'{e}|{n}|{d}')
")"
else
  echo "✗ Neither python3 nor curl is available. Cannot fetch gitmoji data." >&2
  exit 1
fi

if [ -z "$JSON" ]; then
  echo "✗ Failed to fetch or parse gitmoji data from upstream." >&2
  exit 1
fi

# Count entries.
COUNT="$(printf '%s\n' "$JSON" | wc -l | tr -d ' ')"
echo "Fetched ${COUNT} gitmoji entries." >&2

# Write the file.
{
  echo "# gitmoji mapping — <emoji>|<name>|<description>"
  echo "# Source: https://github.com/carloscuesta/gitmoji (packages/gitmojis/src/gitmojis.json)"
  echo "# This file is auto-generated by scripts/update-gitmoji.sh."
  echo "# DO NOT EDIT manually — run \`./scripts/update-gitmoji.sh\` to refresh from upstream."
  printf '%s\n' "$JSON"
} > "$OUTPUT"

echo "✓ Written to $OUTPUT" >&2